spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ImageShop
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

upload:
  path: C:\upload
logging.level:
  org.hibernate.SQL: debug

